
name: PageSpeed Reports

on:
  # schedule:
  #   # Runs daily at 01:30 UTC (01:30 UK winter, 02:30 UK summer)
  #   - cron: '30 2 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  pagespeed:
    runs-on:
      - codebuild-croner-codebuild-pagespeed-github-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm python-dotenv pandas plotly Jinja2

      - name: Inject API Key
        run: echo "PSI_API_KEY=${{ secrets.PSI_API_KEY }}" > .env

      - name: Run PageSpeed batch
        run: |
          mkdir -p reports debug-responses url-lists
          python pagespeed_to_csv.py --url-file urls.txt

      - name: Generate comparison report
        run: python compare_reports.py --with-graphs

      - name: Generate history report
        run: python generate_html_report.py --url-file urls.txt --period 28d --with-graphs

      - name: Generate summary report
        run: python generate_summary_report.py -f urls.txt --period 28d

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pagespeed-reports
          path: |
            reports/**/*.html
            reports/**/*.csv
            debug-responses/**/*.json

